### ISSUE TITLE
Check out some changes please

### ISSUE THREAD

**Issue by opetchey** [opetchey/response_diversity_how_to_measure#16]
In this commit:
https://github.com/opetchey/response_diversity_how_to_measure/commit/b41e5dafebba61b43b0346b57de3a63ee3eb0572
I updated / changed a few things. From the description of that commit:

update
1) I redid the calculations of response diversity in the leary and petchey in a separate repo (a benchmarking one I'm currently developing) and so just bring the resulting dataset in here.
2) I looked carefully at the discrepancy between correlation based response diversity and derivative based. I put a comment about this in the relevant part of the supplement file.

**Comment by SamRPJRoss** [comment]
Thanks for working on that benchmarking part, I think that'll be a really worthwhile addition! 

R.e. the correlation discrepancies because of the GAM fits, it's an interesting observation, but ultimately I'm not sure we can do anything about it because we couldn't fit the GAMs to the same subsets of the data as the Leary & Petchey calculations (e.g. 18-22 degrees would only be 2 or 3 data points in the model [not counting the 3 replicates]). Will keep thinking, but right now I can't think of a way around this.
