### ISSUE TITLE
Create Zenodo release

### ISSUE THREAD

**Issue by SamRPJRoss** [opetchey/response_diversity_how_to_measure#20]
Hi Owen, 

If you have a Zenodo account (https://zenodo.org) would you mind please creating a Zenodo release for this repository so we can cite the supplementary information with DOI in the manuscript? 

To do it, you can log in to Zenodo with your Github account, and go to https://zenodo.org/account/settings/github/ , flip the 'ON' switch for this repository in Zenodo, then create a release on Github, and finally Zenodo should automatically generate a DOI that we can include in the .readme file and can cite in the manuscript. 

Should only take a few mins - sorry I would do it myself but can't access the repository in Zenodo because I'm not the owner. Let me know if you have any difficulty and I can try to help!

**Comment by opetchey** [comment]
Done, thanks for the instructions!
Cheers
Owen
________________________________
From: Sam Ross ***@***.***>
Sent: 24 August 2022 07:40
To: opetchey/response_diversity_how_to_measure ***@***.***>
Cc: Owen Petchey ***@***.***>; Assign ***@***.***>
Subject: [opetchey/response_diversity_how_to_measure] Create Zenodo release (Issue #20)


Hi Owen,

If you have a Zenodo account (https://zenodo.org) would you mind please creating a Zenodo release for this repository so we can cite the supplementary information with DOI in the manuscript?

To do it, you can log in to Zenodo with your Github account, and go to https://zenodo.org/account/settings/github/ , flip the 'ON' switch for this repository in Zenodo, then create a release on Github, and finally Zenodo should automatically generate a DOI that we can include in the .readme file and can cite in the manuscript.

Should only take a few mins - sorry I would do it myself but can't access the repository in Zenodo because I'm not the owner. Let me know if you have any difficulty and I can try to help!

**Comment by SamRPJRoss** [comment]
Thanks Owen! Will submit to MEE tomorrow!
